version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: moradiapp-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - moradiapp-network
    restart: unless-stopped

  backend:
    build: .
    container_name: moradiapp-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/moradiapp
      - SECRET_KEY=chave-super-secreta-para-producao-mudar
      - JWT_SECRET_KEY=jwt-chave-secreta-mudar-em-producao
      - FLASK_ENV=development
    depends_on:
      - mongodb
    networks:
      - moradiapp-network
    restart: unless-stopped

networks:
  moradiapp-network:
    driver: bridge

volumes:
  mongodb_data: